### ISSUE TITLE
Mit rather than gpl?

### ISSUE THREAD

**Issue by baconpaul** [qno/vcv-plugin-cmake-example#2]
Hi! 

I just saw this is gpl. That’s fine for surge but I’m working in a set of mit plugins which have things we may want reused and uses this. Any thoughts about swapping this to mit so folks can use it in no gpl contexts 

if not I’ll swap airwindows to gpl I guess but I always kinda think infrastructural things like this are better if less contagiously licensed to build community erc 

but up to you entirely! I’m happy for my contributions to swap

**Comment by qno** [comment]
Done, changed to MIT.

**Comment by baconpaul** [comment]
Oh great thank you!
